### ISSUE TITLE
Cannot close menu by manipulating state in reducer

### ISSUE THREAD

**Issue by wintermute42** [negomi/redux-burger-menu#10]
I'm trying to close the menu whenever a user clicks on an item within. However, changing burgerMenu.isOpen to false in state doesn't seem to work. There is a similar issue for "react-burger-menu", wich suggests a solution where the isOpen prop is simply set to false on the Menu element (see https://github.com/negomi/react-burger-menu/issues/56). However, this doesn't seem to work in combination with redux-first-router.
Is anyone opening/closing the menu by manipulating state directly, i.e. without dispatching the toggleMenu action?

**Comment by wintermute42** [comment]
I ended up dispatching the action on location change, so this is no longer an issue for me.

**Comment by jonasgrunert** [comment]
I do still run into the same issue, and for me it is not a possibility to fire the dispatch on location change.
Do you have any additional advice?

**Comment by negomi** [comment]
Hey @jonasgrunert, I didn't get around to debugging the original issue, but I'm not sure why this is happening.

If you're able to to reproduce the issue and push the code up to a repo, I can take a look.

**Comment by jonasgrunert** [comment]
Thanks @negomi. My code reside here: [Wahlblock](https://github.com/jonasgrunert/Wahlblock-UI)

**Comment by jonasgrunert** [comment]
Hi @negomi. After some investigation I think I found the issue. The problem does occur while opening the menu via the button. This does not trigger any state update and so react-redux cant find any changes because the menu never got opened. At least thats my personal belief.
Edit:  Did some tests and found that to be the case. Workaround is to 
````
dispatch(toggleMenu(true));
dispatch(toggleMenu(false));
````

For fixing this I would recommend to check your internal dispatching of actions.

**Comment by negomi** [comment]
Hi @jonasgrunert,

Thanks for linking your repo, and sorry it's taken me so long to respond!

I had a chance to check out your code and I see what the problem is. You are wrapping the parent component of the menu, not the menu itself, so the props are not getting passed down by the redux-burger-menu decorator.

So you can either:
1. Wrap your `SideBar` component directly, like this:
```js
const WrappedSideBar = reduxBurgerMenu(SideBar);
const SideMenu = props => (
  <WrappedSideBar
    pageWrapId="main"
    outerContainerId="outer-container"
    styles={burgerMenuStyles}
    customBurgerIcon={
      <div>
        <Icon isDisplay="inline" isSize="medium" className="fa fa-bars fa-2x" />
        <Title isDisplay="inline" isSize={3}>&nbsp;{props.title}</Title>
      </div>
    }
  >
    <AdminMenu routesConfig={props.routesConfig} />
  </WrappedSideBar>
);
```
2. Pass the props down from `SideMenu` to `SideBar`, like this:
```js
const SideMenu = props => (
  <SideBar
    pageWrapId="main"
    outerContainerId="outer-container"
    styles={burgerMenuStyles}
    customBurgerIcon={
      <div>
        <Icon isDisplay="inline" isSize="medium" className="fa fa-bars fa-2x" />
        <Title isDisplay="inline" isSize={3}>&nbsp;{props.title}</Title>
      </div>
    }
    {...props} // <<< here
  >
    <AdminMenu routesConfig={props.routesConfig} />
  </SideBar>
);
```
Either way, you don't need to pass `isOpen={false}`, as redux-burger-menu will add this prop for you and handle it as necessary.

Hope that helps :)
